from quaterion.loss.arcface_loss import ArcFaceLoss
from quaterion.loss.circle_loss import CircleLoss
from quaterion.loss.contrastive_loss import ContrastiveLoss
from quaterion.loss.cos_face_loss import CosFaceLoss
from quaterion.loss.fast_ap_loss import FastAPLoss
from quaterion.loss.group_loss import GroupLoss
from quaterion.loss.multiple_negatives_ranking_loss import MultipleNegativesRankingLoss
from quaterion.loss.online_contrastive_loss import OnlineContrastiveLoss
from quaterion.loss.pairwise_loss import PairwiseLoss
from quaterion.loss.similarity_loss import SimilarityLoss
from quaterion.loss.softmax_loss import SoftmaxLoss
from quaterion.loss.triplet_loss import TripletLoss
